# Generated by Django 6.0.3 on 2026-03-06 10:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(max_length=500)),
                ('file_format', models.CharField(default='GPKG', max_length=50)),
                ('srid', models.IntegerField(blank=True, null=True)),
                ('source_label', models.CharField(blank=True, default='', max_length=200)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='geo_basedat_name_524c44_idx'), models.Index(fields=['current_version'], name='geo_basedat_current_d7fdbf_idx')],
            },
        ),
        migrations.CreateModel(
            name='DerivedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(max_length=500)),
                ('file_format', models.CharField(default='GPKG', max_length=50)),
                ('srid', models.IntegerField(blank=True, null=True)),
                ('source_label', models.CharField(blank=True, default='', max_length=200)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derived_versions', to='geo.basedataset')),
            ],
        ),
        migrations.CreateModel(
            name='AdminBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('extraction_algo_version', models.PositiveIntegerField()),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('external_id', models.CharField(max_length=200)),
                ('admin_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('area_m2', models.FloatField(blank=True, null=True)),
                ('bbox_minx', models.FloatField(blank=True, null=True)),
                ('bbox_miny', models.FloatField(blank=True, null=True)),
                ('bbox_maxx', models.FloatField(blank=True, null=True)),
                ('bbox_maxy', models.FloatField(blank=True, null=True)),
                ('geom_geojson', models.JSONField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='geo.adminboundary')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_boundaries', to='geo.deriveddataset')),
            ],
        ),
        migrations.CreateModel(
            name='StatsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_json', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stats_entries', to='geo.adminboundary')),
                ('derived', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_entries', to='geo.deriveddataset')),
            ],
        ),
        migrations.AddIndex(
            model_name='deriveddataset',
            index=models.Index(fields=['base', 'version'], name='geo_derived_base_id_02af52_idx'),
        ),
        migrations.AddConstraint(
            model_name='deriveddataset',
            constraint=models.UniqueConstraint(fields=('base', 'version'), name='uniq_derived_per_base_version'),
        ),
        migrations.AddIndex(
            model_name='adminboundary',
            index=models.Index(fields=['dataset', 'version'], name='geo_adminbo_dataset_f5fae0_idx'),
        ),
        migrations.AddIndex(
            model_name='adminboundary',
            index=models.Index(fields=['name'], name='geo_adminbo_name_cb1089_idx'),
        ),
        migrations.AddIndex(
            model_name='adminboundary',
            index=models.Index(fields=['admin_level'], name='geo_adminbo_admin_l_61c913_idx'),
        ),
        migrations.AddConstraint(
            model_name='adminboundary',
            constraint=models.UniqueConstraint(fields=('dataset', 'version', 'source', 'external_id'), name='uniq_boundary_id_per_base_version'),
        ),
        migrations.AddIndex(
            model_name='statscache',
            index=models.Index(fields=['derived'], name='geo_statsca_derived_8bceae_idx'),
        ),
        migrations.AddIndex(
            model_name='statscache',
            index=models.Index(fields=['boundary'], name='geo_statsca_boundar_6a1588_idx'),
        ),
        migrations.AddConstraint(
            model_name='statscache',
            constraint=models.UniqueConstraint(fields=('derived', 'boundary'), name='uniq_stats_per_derived_boundary'),
        ),
    ]
