# Generated by Django 6.0.3 on 2026-03-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deriveddataset',
            name='kind',
            field=models.CharField(choices=[('ADMINB', 'Admin Boundaries'), ('LANDUSE', 'Landuse')], default='ADMINB', max_length=10),
        ),
    ]
