# Generated by Django 6.0.3 on 2026-03-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_deriveddataset_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='deriveddataset',
            name='name',
            field=models.CharField(default='name_placeholder', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
